# FROM ghcr.io/janduchscherer104/spatialunderstanding-base:latest
FROM localhost:8000/spatialunderstanding/base:latest

WORKDIR /app

# # Copy application code (needed for editable installs)
# COPY src/ ./src/

# RUN pip install --no-cache-dir -e src/utils -e src/spatial_guidance

